version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    # Mount a volume on our computer onto the container
    # Mounting allows the app to make changes to the files in the directory and persist those changes
    volumes:
      - ./images:/app/images
    # This tells what other services need to be up and running first
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      