version: "3.9"

services:
  db:
    image: postgres 
    restart: always 
    environment: 
      # Reads env vars from .env file
      # Changes to these values require docker compose down, and will wipe the DB
      POSTGRES_USER: ${PSQL_USER} 
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    
